//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosMvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public short OrderTypeId { get; set; }
        public int MenuId { get; set; }
        public short StatusId { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Order Order { get; set; }
        public virtual Status Status { get; set; }
    }
}
