<?xml version="1.0" encoding="utf-8"?><Database Name="main" Class="Main" BaseType="DbLinq.Data.Linq.DataContext" Provider="Sqlite" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="main.Category" Member="Category">
    <Type Name="Category">
      <Column Name="Id" Member="ID" Storage="_id" Type="System.Int32" DbType="integer" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Storage="_name" Type="System.String" DbType="varchar(30)" CanBeNull="false" />
      <Association Name="Category_Menu" Member="Menu" Storage="_menu" ThisKey="ID" OtherKey="CategoryID" Type="Menu" />
    </Type>
  </Table>
  <Table Name="main.Charge" Member="Charge">
    <Type Name="Charge">
      <Column Name="Id" Member="ID" Storage="_id" Type="System.Int32" DbType="integer" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Storage="_name" Type="System.String" DbType="varchar(30)" CanBeNull="true" />
      <Column Name="Value" Storage="_value" Type="System.Single" DbType="real" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="main.Menu" Member="Menu">
    <Type Name="Menu">
      <Column Name="CategoryId" Member="CategoryID" Storage="_categoryID" Type="System.Int32" DbType="integer" CanBeNull="true" />
      <Column Name="Code" Storage="_code" Type="System.String" DbType="text" CanBeNull="false" />
      <Column Name="Id" Member="ID" Storage="_id" Type="System.Int32" DbType="integer" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Storage="_name" Type="System.String" DbType="text" CanBeNull="true" />
      <Column Name="Price" Storage="_price" Type="System.Single" DbType="real" CanBeNull="false" />
      <Association Name="Menu_OrderItem" Member="OrderItem" Storage="_orderItem" ThisKey="ID" OtherKey="MenuID" Type="OrderItem" />
      <Association Name="Category_Menu" Member="Category" Storage="_category" ThisKey="CategoryID" OtherKey="ID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="main.Order" Member="Order">
    <Type Name="Order">
      <Column Name="Created" Storage="_created" Type="System.DateTime" DbType="datetime" CanBeNull="false" />
      <Column Name="CreatedById" Member="CreatedByID" Storage="_createdByID" Type="System.Int32" DbType="integer" CanBeNull="false" />
      <Column Name="DODate" Member="DodAte" Storage="_dodAte" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="Id" Member="ID" Storage="_id" Type="System.Int32" DbType="integer" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MemberId" Member="MemberID" Storage="_memberID" Type="System.Int32" DbType="integer" CanBeNull="true" />
      <Column Name="ReceiptDate" Storage="_receiptDate" Type="System.DateTime" DbType="datetime" CanBeNull="true" />
      <Column Name="TableNo" Storage="_tableNo" Type="System.String" DbType="text" CanBeNull="true" />
      <Column Name="Total" Storage="_total" Type="System.Single" DbType="real" CanBeNull="false" />
      <Association Name="Order_OrderItem" Member="OrderItem" Storage="_orderItem" ThisKey="ID" OtherKey="ParentID" Type="OrderItem" />
      <Association Name="User_Order" Member="User" Storage="_user" ThisKey="CreatedByID" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="main.OrderItem" Member="OrderItem">
    <Type Name="OrderItem">
      <Column Name="Id" Member="ID" Storage="_id" Type="System.Int32" DbType="integer" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MenuId" Member="MenuID" Storage="_menuID" Type="System.Int32" DbType="integer" CanBeNull="false" />
      <Column Name="ParentId" Member="ParentID" Storage="_parentID" Type="System.Int32" DbType="integer" CanBeNull="false" />
      <Column Name="StatusId" Member="StatusID" Storage="_statusID" Type="System.Int32" DbType="integer" CanBeNull="false" />
      <Association Name="Status_OrderItem" Member="Status" Storage="_status" ThisKey="StatusID" OtherKey="ID" Type="Status" IsForeignKey="true" />
      <Association Name="Menu_OrderItem" Member="Menu" Storage="_menu" ThisKey="MenuID" OtherKey="ID" Type="Menu" IsForeignKey="true" />
      <Association Name="Order_OrderItem" Member="Order" Storage="_order" ThisKey="ParentID" OtherKey="ID" Type="Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="main.OrderType" Member="OrderType">
    <Type Name="OrderType">
      <Column Name="Id" Member="ID" Storage="_id" Type="System.Int32" DbType="integer" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Storage="_name" Type="System.String" DbType="varchar(30)" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="main.Role" Member="Role">
    <Type Name="Role">
      <Column Name="Id" Member="ID" Storage="_id" Type="System.Int32" DbType="integer" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Storage="_name" Type="System.String" DbType="varchar(15)" CanBeNull="true" />
      <Association Name="Role_User" Member="User" Storage="_user" ThisKey="ID" OtherKey="RoleID" Type="User" />
    </Type>
  </Table>
  <Table Name="main.Status" Member="Status">
    <Type Name="Status">
      <Column Name="Id" Member="ID" Storage="_id" Type="System.Int32" DbType="integer" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Storage="_name" Type="System.String" DbType="varchar(30)" CanBeNull="false" />
      <Association Name="Status_OrderItem" Member="OrderItem" Storage="_orderItem" ThisKey="ID" OtherKey="StatusID" Type="OrderItem" />
    </Type>
  </Table>
  <Table Name="main.User" Member="User">
    <Type Name="User">
      <Column Name="City" Storage="_city" Type="System.String" DbType="text" CanBeNull="true" />
      <Column Name="Country" Storage="_country" Type="System.String" DbType="text" CanBeNull="true" />
      <Column Name="Displayname" Storage="_displayname" Type="System.String" DbType="text" CanBeNull="true" />
      <Column Name="Id" Member="ID" Storage="_id" Type="System.Int32" DbType="integer" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Password" Storage="_password" Type="System.String" DbType="text" CanBeNull="true" />
      <Column Name="Point" Storage="_point" Type="System.Int32" DbType="integer" CanBeNull="true" />
      <Column Name="Postcode" Storage="_postcode" Type="System.String" DbType="text" CanBeNull="true" />
      <Column Name="RoleId" Member="RoleID" Storage="_roleID" Type="System.Int32" DbType="integer" CanBeNull="true" />
      <Column Name="State" Storage="_state" Type="System.String" DbType="text" CanBeNull="true" />
      <Column Name="Street1" Storage="_street1" Type="System.String" DbType="text" CanBeNull="true" />
      <Column Name="Street2" Storage="_street2" Type="System.String" DbType="text" CanBeNull="true" />
      <Column Name="Username" Storage="_username" Type="System.String" DbType="varchar(30)" CanBeNull="true" />
      <Association Name="User_Order" Member="Order" Storage="_order" ThisKey="ID" OtherKey="CreatedByID" Type="Order" />
      <Association Name="Role_User" Member="Role" Storage="_role" ThisKey="RoleID" OtherKey="ID" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
</Database>